#!/usr/bin/env python3
"""Compile executable artifacts from a Canonical Contract.

This is the deterministic generation step of the Producer pipeline: given a
completed ``canonical-contract.json``, it mechanically compiles

- ``function-core/index.mjs`` - one named async Function export per
  capability: closed input validation from the derived input schema, local
  static-output implementations, and HTTP implementations that build every
  request exactly from the Canonical step bindings (literal URL, fixed query
  preserved inside it, input/prior-response bound query/header/body/multipart
  values, per-step accepted statuses) with zero invented behavior;
- ``mcp-tool/index.mjs`` - literal per-Tool registrations carrying the exact
  derived input/output schemas, annotations, operation policy and summary,
  the dry-run guard, and the two-argument error-normalizer call.

Prose is never invented: Tool titles and descriptions come from the
Agent-authored ``authoring/tool-docs.json`` (``{toolName: {title,
description}}``). Anything the compiler cannot derive honestly (non-static
local outputs, URL-path bindings, non-flat query bindings, missing doc prose)
is reported as ``requires-review`` with an exact reason instead of being
fabricated. The compile report is written to ``compile-report.json`` in the
candidate root; exit code 1 means at least one capability could not be
compiled.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from contract_model import (
    derive_schema_contract,
    operation_summary_for_capability,
)

SCRIPT_DIR = Path(__file__).resolve().parent

FUNCTION_HEADER = """// Generated by compile_artifacts.py from canonical-contract.json; do not edit by hand.
const __inputSchemas = %s;

function __typeOf(value) {
  if (value === null) return 'null';
  if (Array.isArray(value)) return 'array';
  return typeof value;
}

function __matchesType(value, type) {
  if (type === 'integer') return Number.isInteger(value);
  if (type === 'number') return typeof value === 'number' && Number.isFinite(value);
  if (type === 'object') return value !== null && typeof value === 'object' && !Array.isArray(value);
  if (type === 'array') return Array.isArray(value);
  if (type === 'null') return value === null;
  return __typeOf(value) === type;
}

function __validateValue(value, schema, path, errors) {
  if (!schema || typeof schema !== 'object') return;
  const types = Array.isArray(schema.type) ? schema.type : [schema.type];
  if (schema.type && !types.some((type) => __matchesType(value, type))) {
    errors.push(`${path} must be ${types.join('|')}, got ${__typeOf(value)}`);
    return;
  }
  if (schema.enum && !schema.enum.some((item) => JSON.stringify(item) === JSON.stringify(value))) {
    errors.push(`${path} must be one of the declared enum values`);
  }
  if (types.includes('object') && value !== null && typeof value === 'object' && !Array.isArray(value)) {
    const properties = schema.properties || {};
    if (schema.additionalProperties === false) {
      for (const key of Object.keys(value)) {
        if (!(key in properties)) errors.push(`${path}.${key} is not a declared input`);
      }
    }
    for (const name of schema.required || []) {
      if (!(name in value)) errors.push(`${path}.${name} is required`);
    }
    for (const [name, sub] of Object.entries(properties)) {
      if (name in value) __validateValue(value[name], sub, `${path}.${name}`, errors);
    }
  }
  if (types.includes('array') && Array.isArray(value) && schema.items) {
    value.forEach((item, index) => __validateValue(item, schema.items, `${path}[${index}]`, errors));
  }
  if (typeof value === 'string' && schema.pattern && !(new RegExp(schema.pattern).test(value))) {
    errors.push(`${path} must match pattern ${schema.pattern}`);
  }
}

function __validateInput(input, capabilityId) {
  const schema = __inputSchemas[capabilityId];
  const errors = [];
  if (input === null || typeof input !== 'object' || Array.isArray(input)) {
    errors.push('input must be an object');
  } else {
    __validateValue(input, schema, 'input', errors);
  }
  if (errors.length) {
    const error = new Error(`invalid input for ${capabilityId}: ${errors.join('; ')}`);
    error.code = 'INVALID_INPUT';
    error.details = { errors };
    error.retryable = true;
    throw error;
  }
}
"""


def js_literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def compile_local_data(capability: dict[str, Any]) -> dict[str, Any] | None:
    """Assemble the static output object, or None when not fully static."""
    data: dict[str, Any] = {}
    for output in capability.get("outputs", []):
        if not isinstance(output, dict):
            return None
        path = output.get("path")
        domain = output.get("valueDomain")
        if (
            not isinstance(path, list)
            or len(path) != 1
            or not isinstance(path[0], str)
            or not isinstance(domain, dict)
            or domain.get("kind") != "static"
            or not isinstance(domain.get("values"), list)
            or len(domain["values"]) != 1
        ):
            return None
        data[path[0]] = domain["values"][0]
    return data


def binding_value_js(source: dict[str, Any], step_vars: dict[str, str]) -> str | None:
    kind = source.get("kind")
    if kind == "input":
        return f"input[{js_literal(source.get('inputName'))}]"
    if kind == "prior_response":
        variable = step_vars.get(source.get("stepId"))
        if variable is None:
            return None
        path = source.get("path") if isinstance(source.get("path"), list) else []
        access = variable + ".data"
        for segment in path:
            access += f"[{js_literal(segment)}]"
        return access
    if kind == "host_resolved_attachment":
        return (
            f"(context.resolvedAttachments && context.resolvedAttachments[{js_literal(source.get('inputName'))}])"
        )
    return None


def compile_step_js(
    step: dict[str, Any],
    step_vars: dict[str, str],
    index: int,
) -> tuple[str | None, str | None]:
    """Compile one HTTP step; returns (code, error)."""
    variable = f"response{index}"
    step_vars[step.get("stepId")] = variable
    query_entries: list[str] = []
    header_entries: list[str] = []
    body_entries: list[str] = []
    multipart_entries: list[str] = []
    for binding in step.get("bindings", []):
        if not isinstance(binding, dict):
            continue
        source = binding.get("source", {})
        location = binding.get("location")
        path = binding.get("path") if isinstance(binding.get("path"), list) else []
        value_js = binding_value_js(source, step_vars)
        if value_js is None:
            return None, f"unsupported binding source in step {step.get('stepId')}"
        if location == "query":
            if len(path) != 1:
                return None, f"non-flat query binding path {path} is not compilable in this round"
            query_entries.append(f"{js_literal(path[0])}: {value_js}")
        elif location == "header":
            if len(path) != 1:
                return None, f"non-flat header binding path {path} is not compilable in this round"
            header_entries.append(f"{js_literal(str(path[0]).lower())}: {value_js}")
        elif location == "body":
            if len(path) != 1:
                return None, f"nested body binding path {path} is not compilable in this round"
            body_entries.append((path, value_js))
        elif location == "multipart":
            if len(path) != 1:
                return None, f"non-flat multipart binding path {path} is not compilable in this round"
            multipart_entries.append(f"{js_literal(path[0])}: {value_js}")
        elif location == "path":
            return None, "URL path bindings are not compilable in this round"
        elif location is not None:
            return None, f"unsupported binding location {location}"
    header_parts: list[str] = []
    declared_headers = step.get("headers", {}) if isinstance(step.get("headers"), dict) else {}
    for name, value in declared_headers.items():
        header_parts.append(f"{js_literal(str(name).lower())}: {js_literal(value)}")
    for entry in header_entries:
        name, _, value = entry.partition(": ")
        header_parts.append(f"{name}: {value}")
    headers_js = "{" + ", ".join(header_parts) + "}"
    lines = [
        f"  const {variable} = await context.dispatch({js_literal(step.get('url'))}, {{",
        f"    method: {js_literal(step.get('method'))},",
        f"    headers: {headers_js},",
    ]
    if query_entries:
        lines.append("    query: {" + ", ".join(query_entries) + "},")
    if body_entries:
        lines.append("    body: {")
        for path, value_js in body_entries:
            lines.append(f"      {js_literal(path[0])}: {value_js},")
        lines.append("    },")
    if multipart_entries:
        lines.append("    multipart: {" + ", ".join(multipart_entries) + "},")
    lines.append("  });")
    success = step.get("successStatusCodes") or [200]
    lines.append(
        f"  if (!{js_literal(success)}.includes({variable} && {variable}.status)) {{"
    )
    lines.append(
        f"    const error = new Error('upstream request step {step.get('stepId')} was rejected');"
    )
    lines.append("    error.code = 'UPSTREAM_STEP_REJECTED';")
    lines.append(f"    error.details = {{ stepId: {js_literal(step.get('stepId'))}, status: {variable} && {variable}.status }};")
    lines.append("    error.retryable = false;")
    lines.append(f"    error.outcomeKnown = true;")
    lines.append("    throw error;")
    lines.append("  }")
    return "\n".join(lines), None


def compile_function(
    capability: dict[str, Any], schema_contract: dict[str, Any]
) -> tuple[str | None, str | None]:
    capability_id = capability["capabilityId"]
    export = capability["functionExport"]
    implementation = capability.get("implementation", {})
    kind = implementation.get("kind")
    parts = [
        f"export async function {export}(input, context = {{}}) {{",
        f"  __validateInput(input, {js_literal(capability_id)});",
    ]
    if kind == "local":
        data = compile_local_data(capability)
        if data is None:
            return None, "local implementation needs exactly one static value per output"
        parts.append(f"  return {{ status: 'success', data: {js_literal(data)} }};")
    elif kind == "http":
        parts.append(
            "  if (!context || typeof context.dispatch !== 'function') {"
            " const error = new Error('dispatch context is required');"
            " error.code = 'DISPATCH_CONTEXT_REQUIRED'; error.details = {};"
            " error.retryable = false; throw error; }"
        )
        step_vars: dict[str, str] = {}
        steps = implementation.get("steps", [])
        for index, step in enumerate(steps, start=1):
            step_js, error = compile_step_js(step, step_vars, index)
            if error:
                return None, error
            parts.append(step_js)
        output_step = step_vars.get(implementation.get("outputStepId"))
        if output_step is None:
            return None, "implementation.outputStepId must reference a compiled step"
        parts.append(f"  return {{ status: {output_step}.status, data: {output_step}.data }};")
    else:
        return None, f"unsupported implementation kind {kind}"
    parts.append("}")
    return "\n".join(parts), None


ADAPTER_HEADER = """// Generated by compile_artifacts.py from canonical-contract.json; do not edit by hand.
import { McpServer, StdioServerTransport, z } from './runtime.mjs';
import { %s } from '../function-core/index.mjs';
import { normalizeToolError } from '../portable-error-normalizer.mjs';
const server = new McpServer({name: %s, version: '1'});
"""

ADAPTER_FOOTER = """await server.connect(new StdioServerTransport());
"""

REGISTRATION_TEMPLATE = """server.registerTool(%s, {
title: %s,
description: %s,
inputSchema: %s,
outputSchema: %s,
annotations: %s}, async (input, runtimeContext) => {
if (process.env.%s === "1") {
const dryRunResult = {dryRun: true, validatedInput: input, operationPolicy: %s, operationSummary: %s};
return {structuredContent: dryRunResult, content: [{type: 'text', text: JSON.stringify(dryRunResult)}], isError: false}; }
try { const functionResult = await %s(input, runtimeContext);
return {structuredContent: functionResult, content: [{type: 'text', text: JSON.stringify(functionResult)}], isError: false};
} catch (error) { const toolError = normalizeToolError(error, %s);
return {structuredContent: toolError, content: [{type: 'text', text: JSON.stringify(toolError)}], isError: true}; } });
"""


def compile_candidate(candidate: Path) -> dict[str, Any]:
    contract = json.loads((candidate / "canonical-contract.json").read_text(encoding="utf-8"))
    profile_path = candidate / "export-profile.json"
    profile = (
        json.loads(profile_path.read_text(encoding="utf-8"))
        if profile_path.is_file()
        else {}
    )
    schema_contract = derive_schema_contract(contract)
    schemas_by_id = {
        item["capabilityId"]: item
        for item in schema_contract.get("capabilities", [])
        if isinstance(item, dict)
    }
    docs_path = candidate / "authoring" / "tool-docs.json"
    tool_docs: dict[str, Any] = {}
    if docs_path.is_file():
        tool_docs = json.loads(docs_path.read_text(encoding="utf-8"))

    report: dict[str, Any] = {
        "candidate": str(candidate),
        "contractId": contract.get("contractId"),
        "capabilities": [],
        "compiled": True,
    }
    functions_js: list[str] = []
    registrations_js: list[str] = []
    input_schemas: dict[str, Any] = {}
    exports: list[str] = []
    dry_run_variable = profile.get("dryRunEnvironmentVariable")
    if not isinstance(dry_run_variable, str) or not dry_run_variable:
        dry_run_variable = "CODE2SKILL_DRY_RUN"

    for capability in contract.get("capabilities", []):
        if not isinstance(capability, dict) or not isinstance(capability.get("capabilityId"), str):
            continue
        capability_id = capability["capabilityId"]
        tool_name = capability["toolName"]
        entry: dict[str, Any] = {"capabilityId": capability_id, "toolName": tool_name}
        report["capabilities"].append(entry)
        projected = schemas_by_id.get(capability_id)
        if projected is None:
            entry["status"] = "requires-review"
            entry["reason"] = "capability missing from the derived schema contract"
            report["compiled"] = False
            continue
        function_js, error = compile_function(capability, schema_contract)
        if error:
            entry["status"] = "requires-review"
            entry["reason"] = error
            report["compiled"] = False
            continue
        docs = tool_docs.get(tool_name)
        if not isinstance(docs, dict) or not isinstance(docs.get("title"), str) or not isinstance(docs.get("description"), str):
            entry["status"] = "requires-review"
            entry["reason"] = (
                f"authoring/tool-docs.json needs authored title and description for `{tool_name}`; prose is never invented"
            )
            report["compiled"] = False
            continue
        input_schemas[capability_id] = projected["inputSchema"]
        exports.append(capability["functionExport"])
        functions_js.append(function_js)
        policy = json.dumps(
            capability.get("operationPolicy", {}), ensure_ascii=False, separators=(",", ":")
        )
        summary = json.dumps(
            operation_summary_for_capability(capability),
            ensure_ascii=False,
            separators=(",", ":"),
        )
        annotations = (
            "{"
            + ", ".join(
                f"{key}: {str(value).lower()}"
                for key, value in capability.get("annotations", {}).items()
            )
            + "}"
        )
        registrations_js.append(
            REGISTRATION_TEMPLATE
            % (
                js_literal(tool_name),
                js_literal(docs["title"]),
                js_literal(docs["description"]),
                json.dumps(projected["inputSchema"], ensure_ascii=False),
                json.dumps(projected["outputSchema"], ensure_ascii=False),
                annotations,
                dry_run_variable,
                policy,
                summary,
                capability["functionExport"],
                policy,
            )
        )
        entry["status"] = "compiled"

    if report["compiled"]:
        function_core = candidate / "function-core"
        function_core.mkdir(exist_ok=True)
        (function_core / "index.mjs").write_text(
            FUNCTION_HEADER % (json.dumps(input_schemas, ensure_ascii=False),)
            + "\n\n"
            + "\n\n".join(functions_js)
            + "\n",
            encoding="utf-8",
        )
        mcp_tool = candidate / "mcp-tool"
        mcp_tool.mkdir(exist_ok=True)
        server_name = f"{contract.get('contractId', 'code2skill')}-capabilities"
        (mcp_tool / "index.mjs").write_text(
            ADAPTER_HEADER % (", ".join(exports), js_literal(server_name))
            + "".join(registrations_js)
            + ADAPTER_FOOTER,
            encoding="utf-8",
        )
        normalizer_source = SCRIPT_DIR.parent / "assets" / "portable-error-normalizer.mjs"
        if normalizer_source.is_file():
            shutil.copyfile(normalizer_source, candidate / "portable-error-normalizer.mjs")
    return report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("candidate", type=Path)
    parser.add_argument(
        "--report",
        type=Path,
        default=None,
        help="optional path for the machine-readable compile report",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    candidate = args.candidate.resolve()
    try:
        report = compile_candidate(candidate)
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        print(f"ERROR compile_artifacts: {error}", file=sys.stderr)
        return 1
    if args.report is not None:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(
            json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    for capability in report["capabilities"]:
        reason = capability.get("reason")
        print(
            f"{capability['status']}: {capability['capabilityId']}"
            + (f" ({reason})" if reason else "")
        )
    return 0 if report["compiled"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
